paths:
  /api/products/:
    post:
      summary: Crear un producto
      tags:
        - Products
      requestBody:
        description: Campos para crear un producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      responses:
        200:
          description: El producto fue creado satisfactoriamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        500:
          description: Error interno del servidor.
    get:
      summary: Listar todos los productos
      tags:
        - Products
      responses:
        200:
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        500:
          description: Error interno del servidor.
  /api/products/{pid}:
    get:
      summary: Obtener un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            $type: string
      responses:
        200:
          description: El producto fue encontrado satisfactoriamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.
    put:
      summary: Actualiza un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            $type: string
      requestBody:
        description: Campos para actualizar el producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        200:
          description: El producto fue actualizado satisfactoriamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.  
    delete:
      summary: Elimina un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            $type: string
      responses:
        200:
          description: El producto fue eliminado satisfactoriamente.
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.  
components:
  schemas:
    Products:
      type: object
      properties:
        _id: 
          type: string
          description: ID del Producto
        title:
          type: string
          description: Nombre del Producto
        description:
          type: string
          description: Descripción del Producto
        code:
          type: string
          description: Código único del producto
        price:
          type: number
          description: Precio del Producto
        stock: 
          type: number
          description: Stock del Producto  
        category: 
          type: string
          description: Categoria del Producto
        thumbnail: 
          type: string
          description: Imagen del Producto
        owner: 
          type: string
          description: Creador del Producto    
      example:   
        _id: 64a3ab2007150d554af7a738
        title: Dulce de leche de coco
        description: Dulce a base de leche de coco vegano
        code: IJK456  
        price: 1100
        stock: 45
        category: Celíacos
        thumbnail: 1688447776387dulce_leche_coco_vegan.jpg
        owner: admin
  
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del Producto
        description:
          type: string
          description: Descripción del Producto
        code:
          type: string
          description: Código único del producto
        price:
          type: number
          description: Precio del Producto
        stock: 
          type: number
          description: Stock del Producto  
        category: 
          type: string
          description: Categoria del Producto
        thumbnail: 
          type: string
          description: Imagen del Producto
        owner: 
          type: string
          description: Creador del Producto
      example:   
        _id: 64a3ab2007150d554af7a738
        title: Dulce de leche de coco
        description: Dulce a base de leche de coco vegano
        code: IJK456  
        price: 1100
        stock: 45
        category: Celíacos
        thumbnail: 1688447776387dulce_leche_coco_vegan.jpg
        owner: admin   
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del Producto
        description:
          type: string
          description: Descripción del Producto
        code:
          type: string
          description: Código único del producto
        price:
          type: number
          description: Precio del Producto
        stock: 
          type: number
          description: Stock del Producto  
        category: 
          type: string
          description: Categoria del Producto
        thumbnail: 
          type: string
          description: Imagen del Producto
        owner: 
          type: string
          description: Creador del Producto
      example:   
        _id: 64a3ab2007150d554af7a738
        title: Dulce de leche de coco
        description: Dulce a base de leche de coco vegano
        code: IJK456  
        price: 1100
        stock: 45
        category: Celíacos
        thumbnail: 1688447776387dulce_leche_coco_vegan.jpg
        owner: admin   